---
- hosts: vd
  gather_facts: true
  tasks:
    - name: Obtener la fecha de inicio
      set_fact:
        start_time: "{{ ansible_date_time.epoch }}"

    - name: Obtener actualizaciones pendientes
      win_updates:
        state: installed
        category_names:
          - SecurityUpdates
          - UpdateRollups
        register: updates_result

    - name: Crear archivo de actualizaciones realizadas
      copy:
        content: "{{ updates_result.updates | to_nice_json }}\n"
        dest: "{{ ansible_env.HOME }}/actualizaciones_realizadas.json"
      when: updates_result.updates is defined and updates_result.updates | length > 0

    - name: Obtener la fecha de finalizaci贸n
      set_fact:
        end_time: "{{ ansible_date_time.epoch }}"

    - name: Calcular la duraci贸n de la actualizaci贸n
      set_fact:
        duration_seconds: "{{ end_time | int - start_time | int }}"
        duration_formatted: "{{ duration_seconds | to_nice_duration }}"

    - name: Guardar la duraci贸n en un archivo
      copy:
        content: "{{ duration_formatted }}\n"
        dest: "{{ ansible_env.HOME }}/duracion_actualizacion.txt"
